name: african_cuisine
description: "A new Flutter project."
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.1.0

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  fluttertoast: ^8.2.12
  animations: ^2.0.11
  image_picker: ^1.1.2
  file_picker: ^10.1.9
  flutter_multi_formatter: ^2.13.7
  shared_preferences: ^2.5.3
  http: ^1.4.0
  google_maps_flutter: ^2.12.2
  speech_to_text: ^7.0.0
  phone_numbers_parser: ^9.0.3
  geolocator: ^11.0.0
  smooth_page_indicator: ^1.2.1
  firebase_messaging: ^15.2.9
  flutter_stripe: ^11.5.0
  geocoding: ^4.0.0
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.0
  firebase_storage: ^12.4.7
  cloud_firestore: ^5.6.9
  url_launcher: ^6.3.1
  emoji_picker_flutter: ^4.3.0
  flutter_rating_bar: ^4.0.1
  cloud_functions: ^5.6.0
  intl: ^0.20.2
  location: ^8.0.1
  flutter_displaymode: ^0.6.0
  firebase_crashlytics: ^4.3.9
  vibration: ^3.1.3
  just_audio: ^0.10.4
  confetti: ^0.8.0
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_api_headers: ^1.6.0
  lottie: ^3.3.1
  shimmer: ^3.0.0
  flutter_local_notifications: ^19.3.1
  flutter_ringtone_player: ^4.0.0+4
  image_cropper: ^9.1.0
  sms_autofill: ^2.4.1
  firebase_analytics: ^11.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
dependency_overrides:
  http: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
